import { useState } from 'react';
import { ArrowLeft, Eye, Save } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button, Card, Dialog, StatusToast } from '../../shared/ui';

export function ContentEditorPage() {
  const navigate = useNavigate();
  const [saved, setSaved] = useState(false);
  const [previewOpen, setPreviewOpen] = useState(false);
  return <div className="mx-auto max-w-5xl animate-rise"><button onClick={() => navigate('/teacher/content')} className="mb-5 inline-flex min-h-11 items-center gap-2 rounded-xl px-2 font-bold text-stone-600"><ArrowLeft className="h-5 w-5" /> К материалам</button><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Конструктор контента</p><h1 className="page-title mt-3">Новый учебный модуль</h1></div><div className="flex gap-2"><Button variant="outline" onClick={() => setPreviewOpen(true)}><Eye className="h-4 w-4" /> Предпросмотр</Button><Button onClick={() => setSaved(true)}><Save className="h-4 w-4" /> Сохранить</Button></div></div><Card className="mt-6 p-6 sm:p-8"><form className="space-y-6" onSubmit={(e) => e.preventDefault()}><div><label className="field-label" htmlFor="module-title">Название модуля</label><input id="module-title" className="field-control" defaultValue="Разложение на множители" /></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="field-label" htmlFor="subject">Предмет</label><select id="subject" className="field-control"><option>Математика</option><option>Физика</option></select></div><div><label className="field-label" htmlFor="grade">Класс</label><select id="grade" className="field-control"><option>9 класс</option><option>8 класс</option><option>10 класс</option></select></div></div><div><label className="field-label" htmlFor="description">Короткое описание</label><textarea id="description" rows="4" className="field-control py-3" defaultValue="Научимся видеть общий множитель и применять формулу разности квадратов." /></div><fieldset><legend className="field-label">Навыки-пререквизиты</legend><div className="grid gap-3 sm:grid-cols-2">{['Линейные уравнения', 'Степени', 'Формулы сокращённого умножения', 'Дроби'].map((item, i) => <label key={item} className="flex min-h-12 items-center gap-3 rounded-2xl border border-stone-200 px-4"><input type="checkbox" defaultChecked={i < 2} className="h-4 w-4 accent-lavender-600" />{item}</label>)}</div></fieldset><div><label className="field-label" htmlFor="theory">Теория и объяснение</label><textarea id="theory" rows="8" className="field-control py-3" defaultValue={'Разность квадратов — выражение вида a² − b².\n\nФормула: a² − b² = (a − b)(a + b).'} /></div></form></Card>
    <Dialog open={previewOpen} onClose={() => setPreviewOpen(false)} title="Предпросмотр модуля" description="Так материал увидит ученик." size="lg" footer={<><Button variant="ghost" onClick={() => setPreviewOpen(false)}>Вернуться к редактору</Button><Button onClick={() => { setPreviewOpen(false); setSaved(true); }}>Сохранить черновик</Button></>}><article><span className="rounded-full bg-lavender-100 px-3 py-1.5 text-xs font-bold text-lavender-700">Математика · 9 класс</span><h3 className="mt-5 font-display text-3xl font-semibold">Разложение на множители</h3><p className="mt-4 text-stone-600">Научимся видеть общий множитель и применять формулу разности квадратов.</p><div className="mt-7 rounded-3xl bg-ink p-7 text-center font-display text-2xl font-semibold text-white">a² − b² = (a − b)(a + b)</div><div className="mt-5 rounded-2xl bg-mint-100 p-5 text-sm leading-7"><strong>Как запомнить:</strong> одинаковые скобки, но знаки разные — минус и плюс.</div></article></Dialog>
    <StatusToast message={saved ? 'Черновик сохранён' : ''} onClose={() => setSaved(false)} />
  </div>;
}
