import { useState } from 'react';
import { ArrowLeft, Mail, MessageSquareText, Target } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, Card, Dialog, ProgressBar, StatusToast } from '../../shared/ui';

export function StudentDetailsPage() {
  const navigate = useNavigate();
  const { studentId } = useParams();
  const [commentOpen, setCommentOpen] = useState(false);
  const [toast, setToast] = useState('');
  return <div className="mx-auto max-w-6xl animate-rise"><button onClick={() => navigate('/teacher/classes/9a')} className="mb-5 inline-flex min-h-11 items-center gap-2 rounded-xl px-2 font-bold text-stone-600"><ArrowLeft className="h-5 w-5" /> К классу</button><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-3xl bg-lavender-200 text-xl font-extrabold text-lavender-700">А</span><div><p className="eyebrow">Ученик #{studentId}</p><h1 className="mt-1 text-3xl font-extrabold">Айару С.</h1><p className="text-stone-500">9A · цель: итоговый экзамен</p></div></div><Button variant="outline" onClick={() => setCommentOpen(true)}><MessageSquareText className="h-5 w-5" /> Оставить комментарий</Button></div><div className="mt-8 grid gap-6 lg:grid-cols-[0.7fr_1.3fr]"><div className="space-y-6"><Card className="p-6"><Target className="h-6 w-6 text-lavender-600" /><p className="mt-5 text-sm text-stone-500">Готовность к цели</p><p className="font-display text-4xl font-semibold">78%</p><ProgressBar className="mt-5" value={78} /></Card><Card className="p-6"><h2 className="text-xl font-extrabold">Контакты</h2><p className="mt-4 flex items-center gap-3 text-sm text-stone-600"><Mail className="h-5 w-5" /> student@sanaq.kz</p></Card></div><Card className="p-6 sm:p-8"><p className="eyebrow">По навыкам</p><h2 className="mt-2 text-2xl font-extrabold">Что происходит сейчас</h2><div className="mt-7 space-y-6"><ProgressBar value={92} label="Линейные уравнения" tone="mint" /><ProgressBar value={76} label="Формулы сокращённого умножения" /><ProgressBar value={58} label="Разложение на множители" tone="coral" /><ProgressBar value={32} label="Квадратные уравнения" tone="coral" /></div><div className="mt-8 rounded-2xl bg-[#FFE8E2] p-5"><p className="font-bold text-[#8E3929]">Точка внимания</p><p className="mt-2 text-sm text-stone-700">Айару трижды выбрала квадрат разности вместо разности квадратов. Поможет сравнение двух формул рядом.</p></div></Card></div>
    <Dialog open={commentOpen} onClose={() => setCommentOpen(false)} title="Комментарий ученику" description="Комментарий появится в маршруте Айару и останется доступен учителю." footer={<><Button variant="ghost" onClick={() => setCommentOpen(false)}>Отмена</Button><Button onClick={() => { setCommentOpen(false); setToast('Комментарий сохранён и отправлен ученику'); }}>Отправить</Button></>}><div><label className="field-label" htmlFor="teacher-comment">Сообщение</label><textarea id="teacher-comment" rows="5" className="field-control py-3" defaultValue="Айару, ты хорошо справляешься с базовыми преобразованиями. Обрати внимание на разницу между двумя похожими формулами — я добавила короткое повторение." /><label className="mt-4 flex min-h-11 cursor-pointer items-center gap-3 text-sm font-semibold"><input type="checkbox" defaultChecked className="h-5 w-5 accent-lavender-600" /> Добавить в план на завтра</label></div></Dialog>
    <StatusToast message={toast} onClose={() => setToast('')} />
  </div>;
}
