import { LockKeyhole, Play, Route, Sparkles } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button, Card, ProgressBar } from '../../shared/ui';
import { learningModules } from '../../shared/data/mockData';

export function LearningPathPage() {
  const navigate = useNavigate();
  return <div className="mx-auto max-w-5xl animate-rise"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Цель: экзамен · 15 октября</p><h1 className="page-title mt-3">Твой маршрут</h1><p className="mt-3 text-stone-600">SANAQ перестраивает порядок после каждой учебной сессии.</p></div><span className="inline-flex items-center gap-2 self-start rounded-2xl bg-lavender-100 px-4 py-3 text-sm font-bold text-lavender-700"><Route className="h-5 w-5" /> 3 из 12 шагов</span></div>
    <div className="relative mt-10 space-y-5 before:absolute before:bottom-10 before:left-[31px] before:top-10 before:w-0.5 before:bg-stone-200 sm:before:left-[39px]">{learningModules.map((module, index) => <Card key={module.id} className={`relative ml-16 p-5 sm:ml-20 sm:p-7 ${module.status === 'locked' ? 'opacity-65' : ''}`}><span className={`absolute -left-[66px] top-7 z-10 grid h-12 w-12 place-items-center rounded-2xl border-4 border-canvas font-display text-sm font-semibold sm:-left-[86px] sm:h-16 sm:w-16 ${module.status === 'active' ? 'bg-lime text-ink' : module.status === 'locked' ? 'bg-stone-300 text-stone-600' : 'bg-lavender-600 text-white'}`}>{module.status === 'locked' ? <LockKeyhole className="h-5 w-5" /> : `0${index + 1}`}</span><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-extrabold">{module.title}</h2>{module.status === 'active' && <span className="inline-flex items-center gap-1 rounded-full bg-lime/30 px-2.5 py-1 text-xs font-bold"><Sparkles className="h-3 w-3" /> Сейчас</span>}</div><p className="mt-2 text-sm text-stone-600">{module.description}</p><p className="mt-3 text-xs font-bold text-stone-400">{module.duration} · {module.lessons} урока</p>{module.progress > 0 && <ProgressBar className="mt-5 max-w-xl" value={module.progress} />}</div><Button variant={module.status === 'active' ? 'primary' : 'outline'} disabled={module.status === 'locked'} onClick={() => navigate(`/student/learn/${module.id}`)}>{module.progress ? 'Продолжить' : 'Начать'} <Play className="h-4 w-4" /></Button></div></Card>)}</div>
  </div>;
}
