import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Lightbulb, XCircle } from 'lucide-react';
import { Button, Card, ProgressBar } from '../../shared/ui';

export function TaskPage() {
  const [selected, setSelected] = useState(null);
  const [checked, setChecked] = useState(false);
  const [mode, setMode] = useState('short');
  const [hintVisible, setHintVisible] = useState(false);
  const navigate = useNavigate();
  const correct = selected === 0;
  const answers = ['(x − 5)(x + 5)', '(x − 25)(x + 1)', '(x − 5)²', 'x(x − 25)'];
  return <div className="mx-auto max-w-4xl animate-rise"><div className="mb-6"><p className="eyebrow">Практика · 1 из 4</p><h1 className="mt-2 text-3xl font-extrabold">Закрепим формулу</h1><ProgressBar className="mt-5" value={25} /></div><Card className="p-6 sm:p-10"><p className="text-sm font-bold text-lavender-600">Разложение на множители</p><h2 className="mt-4 text-2xl font-extrabold sm:text-3xl">Разложите выражение x² − 25.</h2><fieldset className="mt-8"><legend className="sr-only">Варианты ответа</legend><div className="grid gap-3 sm:grid-cols-2">{answers.map((answer, index) => { const active = selected === index; const stateClass = checked && active ? (correct ? 'border-mint-500 bg-mint-100' : 'border-coral bg-[#FFE8E2]') : active ? 'border-lavender-500 bg-lavender-100' : 'border-stone-200'; return <label key={answer} className={`flex min-h-16 cursor-pointer items-center gap-3 rounded-2xl border-2 p-4 font-bold ${stateClass}`}><input type="radio" name="task-answer" className="sr-only" disabled={checked} checked={active} onChange={() => setSelected(index)} /><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-paper text-sm">{String.fromCharCode(65 + index)}</span>{answer}{checked && active && (correct ? <CheckCircle2 className="ml-auto h-5 w-5 text-mint-700" /> : <XCircle className="ml-auto h-5 w-5 text-[#A74735]" />)}</label>; })}</div></fieldset>
      {!checked ? <><div className="mt-8 flex items-center justify-between gap-3"><button onClick={() => setHintVisible((value) => !value)} className="inline-flex min-h-11 items-center gap-2 rounded-xl px-3 font-bold text-stone-600 hover:bg-stone-100" aria-expanded={hintVisible}><Lightbulb className="h-5 w-5" /> {hintVisible ? 'Скрыть подсказку' : 'Дать подсказку'}</button><Button disabled={selected === null} onClick={() => setChecked(true)}>Проверить</Button></div>{hintVisible && <div className="mt-4 flex gap-3 rounded-2xl bg-lime/25 p-5" role="status"><Lightbulb className="mt-0.5 h-5 w-5 shrink-0 text-[#52670A]" /><p className="text-sm font-semibold leading-6">Попробуй представить число 25 как квадрат другого числа. После этого выражение станет похоже на формулу a² − b².</p></div>}</> : <div className={`mt-8 rounded-3xl p-6 ${correct ? 'bg-mint-100' : 'bg-[#FFE8E2]'}`} role="status"><p className="text-lg font-extrabold">{correct ? 'Верно — навык стал сильнее' : 'Почти. Здесь спрятана разность квадратов'}</p><div className="mt-4 flex flex-wrap gap-2">{[['short', 'Коротко'], ['steps', 'Пошагово'], ['life', 'На примере']].map(([value, label]) => <button key={value} onClick={() => setMode(value)} className={`min-h-11 rounded-xl px-4 text-sm font-bold ${mode === value ? 'bg-ink text-white' : 'bg-paper'}`}>{label}</button>)}</div><p className="mt-4 leading-7">{mode === 'short' && '25 — это 5². Поэтому x² − 5² = (x − 5)(x + 5).'}{mode === 'steps' && '1. Представь 25 как 5². 2. Примени a² − b². 3. Получи две скобки с разными знаками.'}{mode === 'life' && 'Если из квадрата x × x убрать квадрат 5 × 5, оставшуюся площадь можно превратить в прямоугольник (x − 5) × (x + 5).'}</p><div className="mt-6 flex justify-end"><Button variant={correct ? 'success' : 'dark'} onClick={() => navigate('/student/dashboard')}>Обновить маршрут <ArrowRight className="h-5 w-5" /></Button></div></div>}
    </Card></div>;
}
